import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "./providers";
import "./globals.css";
import NavbarMenu from "@/components/navbar/NavbarMenu";
import LoggedInButton from "@/components/navbar/auth/LoggedInButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <header className=" p-8 ">
            <NavbarMenu>
              <LoggedInButton />
            </NavbarMenu>
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
